name: tartim
# SUMMARY: Kapsamlı tartım uygulaması için Flutter package tanımı ve bağımlılıkları.
description: "A comprehensive Flutter package for weight measurement functionality with Bluetooth integration, data synchronization, and local storage capabilities."
version: 0.0.1
homepage: https://github.com/hasanhuseyinyetkiner/tartim

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # State management
  get: ^4.6.6
  # Bluetooth functionality
  flutter_blue_plus: ^1.32.12
  # HTTP requests
  http: ^1.2.2
  # Local storage
  shared_preferences: ^2.3.2
  get_storage: ^2.1.1
  # Database
  sqflite: ^2.4.1
  # Date formatting
  intl: ^0.19.0
  # Path utilities
  path: ^1.9.0
  # Charts and animations
  lottie: ^3.1.2
  fl_chart: ^0.69.0
  # Connectivity
  connectivity_plus: ^6.0.3
  # Permissions
  permission_handler: ^11.3.1
  # Image picker
  image_picker: ^1.0.4
  # Staggered animations
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/animations/
    - assets/images/
